server:
  port: 8085

spring:
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: notification-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      enable-auto-commit: false

      properties:
        spring:
          json:
            trusted:
              packages: "*"
            value:
              default:
                type: com.kodewala.order.event.OrderCreatedEvent
