server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micromini
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      acks: all
      retries: 3

      properties:
        retry:
          backoff:
            ms: 1000
        enable:
          idempotence: true
        max:
          in:
            flight:
              requests:
                per:
                  connection: 5

    consumer:
      group-id: pickup-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      enable-auto-commit: false

      properties:
        spring:
          json:
            trusted:
              packages: "*"
            value:
              default:
                type: com.kodewala.order.event.OrderCreatedEvent
